# This workflow will do a clean install of node dependencies, build the source code and run tests and deploy to binary repo
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: ['!develop', '!uat']
  pull_request:
    branches: 
    - '*'

jobs:
  build:
    name: "build and test"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: foodpantry-labelbuster_node_modules-${{ hashFiles('package.json') }}
          restore-keys: |
            foodpantry-labelbuster_node_modules-${{ hashFiles('package.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
